---
  - name: "update apt packages."
    become: true
    apt:
      update_cache: yes

  - name: download build essentials
    become: true
    apt:
      name: build-essential
      upgrade: yes    

  - name: Install Nodejs and NPM
    apt: 
      name: ["nodejs", "npm"]
      state: latest

  - name: "install n"
    become: true
    npm:
      name: n
      global: yes
      production: yes

  - name: Install node 13.8
    become: true
    shell: n 13.8.0

  - name: "install pm2"
    become: true
    npm:
      name: pm2
      global: yes
      production: yes
      state: present
