---
  - name: "update apt packages."
    become: true
    apt:
      update_cache: yes

  - name: download build essentials
    apt:
      name: build-essential
      state: latest    

  - name: Install Nodejs and NPM
    apt: 
      name: ["nodejs", "npm"]
      state: latest

  - name: instann node manager
    become: true
    npm:
      name: n
      global: yes
      production: yes
    
  - name: install nodejs 13.8
    become: true
    shell: n 13.8.0

  - name: donwload PM2 
    shell: npm install pm2 -g && pm2 update
