- name: creates directory for code
  file:
    path: ~/code
    state: directory

- name: extracting code
  unarchive:
    src: artifact.tar.gz
    dest: ~/code

- name: Installing modules
  command: npm install
  args:
    chdir: ~/code

- name: pm2 start npm -- start
  command: pm2 start npm -- start
  args:
    chdir: ~/code