- name: creates directory for backend
  file:
    path: ~/code
    state: directory

- name: extracting code
  unarchive:
    src: artifact.tar.gz
    dest: ~/code

- name: Installing modules
  command: npm install
  args:
    chrdir: ~/code

- name: Starting Server
  command: pm2 start npm -- start
  args:
    chrdir: ~/code/dist
