- name: creates directory for code
  file:
    path: ~/code
    state: directory

- name: extracting code
  unarchive:
    src: artifact.tar.gz
    dest: ~/code

- name: Installing modules
  command: |
    cd ~/code
    npm install

- name: Starting Server
  command: |
    cd ~/code
    pm2 start npm -- start
